version: "3"
services:
  frontend:
    build:
      dockerfile: ../unit_test/Dockerfile.frontend
      context: ../${FRONTEND_DIR}
    command: "test"
    volumes:
      - "../${FRONTEND_DIR}:/code"
      - /code/node_modules
  backend:
    build:
      dockerfile: ../unit_test/Dockerfile.backend
      context: ../${BACKEND_DIR}
    command: "test"
    volumes:
      - "../${BACKEND_DIR}:/code"
