version: "3"
services:
  frontend:
    build:
      dockerfile: ../unit_test/Dockerfile.frontend
      context: ../${FRONTEND_DIR}
    command: "test"
    environment:
      - "CI=1"
    volumes:
      - "../${FRONTEND_DIR}:/code"
      - "REACT_APP_RECAPTCHA_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      - /code/node_modules
  backend:
    build:
      dockerfile: ../unit_test/Dockerfile.backend
      context: ../${BACKEND_DIR}
    command: "test"
    volumes:
      - "../${BACKEND_DIR}:/code"
      - RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
