version: "3"
services:
  frontend:
    build:
      dockerfile: ./unit_test/Dockerfile.frontend
      context: ..
    command: "test"
    environment:
      - "CI=1"
      - "REACT_APP_RECAPTCHA_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
    volumes:
      - "..:/code"
      - /code/node_modules
  backend:
    build:
      dockerfile: ./unit_test/Dockerfile.backend
      context: ..
    command: "test"
    environment:
      - RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    volumes:
      - "..:/code"
