version: "3"
services:
  # lint:
  #   depends_on:
  #     - frontend_lint
  #     - backend_lint
  frontend_lint:
    build:
      dockerfile: ../Dockerfile.frontend.lint
      context: ${FRONTEND_DIR}
    command: "fix"
    volumes:
      - "${FRONTEND_DIR}:/code"
  backend_lint:
    build:
      dockerfile: ../Dockerfile.backend.lint
      context: ${BACKEND_DIR}
    command: "fix"
    volumes:
      - "${BACKEND_DIR}:/code"
