version: "3"
services:
  frontend:
    build:
      dockerfile: ./lint/Dockerfile.frontend
      context: ..
    command: "fix"
    volumes:
      - "..:/code"
  backend:
    build:
      dockerfile: ./lint/Dockerfile.backend
      context: ..
    command: "fix"
    volumes:
      - "..:/code"
